### ISSUE TITLE
UnboundLocalError: local variable 'time_model' referenced before assignment

### ISSUE THREAD

**Issue by pacesm** [EOX-A/ngeo-b#50]
Apparently if the if the execution passes trough this if-branch the `time_model` variable is not assigned and the execution fails.

https://github.com/EOX-A/ngeo-b/blob/401b8e44a4a42a0449cd71be65107f4a730f412b/ngeo_browse_server/control/queries.py#L310-L314

```
$ sudo -u apache python /var/www/ngeo/ngeo_browse_server_instance/manage.py ngeo_purge --layer=...
INFO: Starting browse layer purging from command line.
INFO: Deleting '91643' browses from database.
WARNING: No MapCache Time object found for time: ...
Traceback (most recent call last):
  File "/var/www/ngeo/ngeo_browse_server_instance/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.6/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.6/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.6/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/lib/python2.6/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.6/site-packages/ngeo_browse_server/control/management/commands/ngeo_purge.py", line 86, in handle
    self._handle(browse_layer_id, browse_type)
  File "/usr/lib/python2.6/site-packages/ngeo_browse_server/control/management/commands/ngeo_purge.py", line 130, in _handle
    unseed=False
  File "/usr/lib/python2.6/site-packages/ngeo_browse_server/control/queries.py", line 361, in remove_browse
    if time_model.start_time == time_model.end_time:
UnboundLocalError: local variable 'time_model' referenced before assignment
Exception AttributeError: "'NoneType' object has no attribute 'destroy_geom'"Exception in thread Thread-1 (most likely raised during interpreter shutdown): in  ignored
```

**Comment by Schpidi** [comment]
it seems that we're in an inconsistent state here as the main db and mapcache db are out of sync,

maybe try to add the command to regenerate the mapcache sqlite file https://github.com/EOX-A/ngeo-b/compare/async-mapcache?expand=1#diff-c2468f926e93dd5efcac045b89cb46e3522045bb693f2dfb32976a9acffdec9b

**Comment by lubojr** [comment]
Added the sync command to branch-4-1 and fixes the faulty elif branch returning from the function.
